/** ISTAT province names → official two-letter codes (sigle automobilistiche). */
const PROVINCES: Record<string, string> = {
  agrigento: "AG",
  alessandria: "AL",
  ancona: "AN",
  aosta: "AO",
  "valle d'aosta": "AO",
  arezzo: "AR",
  "ascoli piceno": "AP",
  asti: "AT",
  avellino: "AV",
  bari: "BA",
  "barletta-andria-trani": "BT",
  belluno: "BL",
  benevento: "BN",
  bergamo: "BG",
  biella: "BI",
  bologna: "BO",
  bolzano: "BZ",
  "alto adige": "BZ",
  brescia: "BS",
  brindisi: "BR",
  cagliari: "CA",
  caltanissetta: "CL",
  campobasso: "CB",
  caserta: "CE",
  catania: "CT",
  catanzaro: "CZ",
  chieti: "CH",
  como: "CO",
  cosenza: "CS",
  cremona: "CR",
  crotone: "KR",
  cuneo: "CN",
  enna: "EN",
  fermo: "FM",
  ferrara: "FE",
  firenze: "FI",
  foggia: "FG",
  "forlì-cesena": "FC",
  frosinone: "FR",
  genova: "GE",
  gorizia: "GO",
  grosseto: "GR",
  imperia: "IM",
  isernia: "IS",
  "l'aquila": "AQ",
  "la spezia": "SP",
  latina: "LT",
  lecce: "LE",
  lecco: "LC",
  livorno: "LI",
  lodi: "LO",
  lucca: "LU",
  macerata: "MC",
  mantova: "MN",
  "massa-carrara": "MS",
  matera: "MT",
  messina: "ME",
  milano: "MI",
  modena: "MO",
  "monza e della brianza": "MB",
  napoli: "NA",
  novara: "NO",
  nuoro: "NU",
  oristano: "OR",
  padova: "PD",
  palermo: "PA",
  parma: "PR",
  pavia: "PV",
  perugia: "PG",
  "pesaro e urbino": "PU",
  pescara: "PE",
  piacenza: "PC",
  pisa: "PI",
  pistoia: "PT",
  pordenone: "PN",
  potenza: "PZ",
  prato: "PO",
  ragusa: "RG",
  ravenna: "RA",
  "reggio calabria": "RC",
  "reggio emilia": "RE",
  rieti: "RI",
  rimini: "RN",
  roma: "RM",
  rovigo: "RO",
  salerno: "SA",
  sassari: "SS",
  savona: "SV",
  siena: "SI",
  siracusa: "SR",
  sondrio: "SO",
  "sud sardegna": "SU",
  taranto: "TA",
  teramo: "TE",
  terni: "TR",
  torino: "TO",
  trapani: "TP",
  trento: "TN",
  treviso: "TV",
  trieste: "TS",
  udine: "UD",
  varese: "VA",
  venezia: "VE",
  "verbano-cusio-ossola": "VB",
  vercelli: "VC",
  verona: "VR",
  "vibo valentia": "VV",
  vicenza: "VI",
  viterbo: "VT",
};

export function provinceCode(name: string | null | undefined): string {
  if (!name) return "";
  const clean = name
    .toLowerCase()
    .replace(
      /^(provincia (di|del|della|dell')\s*|città metropolitana di\s*|libero consorzio comunale di\s*)/i,
      "",
    )
    .trim();
  if (/^[a-z]{2}$/i.test(clean)) return clean.toUpperCase();
  return PROVINCES[clean] ?? name;
}
